/**
 * Writes the generated atlas.
 *
 * Run with `pnpm --filter @vertex/ui atlas`. The output is committed, for the
 * reason `tokens/build.ts` gives about the palette: consuming a built
 * `@vertex/ui` must never require running a generator, and a change to the
 * geometry has to arrive as a diff somebody can be shown.
 *
 * **Natural Earth, through `world-atlas`, and not OpenStreetMap.** Natural
 * Earth is public domain: no attribution to carry, no licence to satisfy, and
 * nothing to work out about what a closed-source product owes a data set it
 * ships inside itself. OSM's boundaries are ODbL, whose share-alike terms on
 * derived data are a question worth not opening for a country outline.
 *
 * The cut is by **edition**: `SYS-14` says the geometry ships with the product,
 * and a Syrian shop has no use for the provinces of Brazil. Widening the region
 * is editing the list below and regenerating.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { GeometryObject, Properties, Topology } from 'topojson-specification';

import { narrow } from './topology.js';

const require = createRequire(import.meta.url);

/**
 * ISO 3166-1 numeric codes, which is what `world-atlas` uses as an id.
 *
 * Syria and everything it touches, plus what a reader needs on screen for the
 * country to be recognisable as itself: the Mediterranean coast is only a coast
 * if Cyprus is there, and a branch near the border is only near a border if the
 * country on the other side is drawn.
 */
const REGION: ReadonlyMap<string, string> = new Map([
  ['760', 'Syria'],
  ['792', 'Türkiye'],
  ['368', 'Iraq'],
  ['400', 'Jordan'],
  ['422', 'Lebanon'],
  ['376', 'Israel'],
  ['275', 'Palestine'],
  ['196', 'Cyprus'],
  ['682', 'Saudi Arabia'],
  ['414', 'Kuwait'],
  ['818', 'Egypt'],
]);

const HOME = '760';

/**
 * 50m for the region and 110m for the world.
 *
 * The region is what somebody looks at, so it carries the detail. The world is
 * only there so that zooming out lands on a planet rather than on a country
 * floating in nothing, and at that size 110m is already finer than the screen.
 */
const REGION_SOURCE = 'world-atlas/countries-50m.json';
const WORLD_SOURCE = 'world-atlas/land-110m.json';

function read(specifier: string): Topology {
  return JSON.parse(readFileSync(require.resolve(specifier), 'utf8')) as Topology;
}

/**
 * JSON inside a raw template literal, rather than a JavaScript object literal.
 *
 * Two reasons, both measurable. A hundred thousand numbers written as source
 * are a hundred thousand expressions for the compiler to infer and the linter
 * to walk; as a string they are one. And a large `JSON.parse` is faster at run
 * time than the equivalent literal, because the parser knows it is reading data
 * and the JavaScript engine has to assume it might not be.
 */
function embed(value: unknown): string {
  return JSON.stringify(value).replace(/`/g, '\\u0060').replace(/\$\{/g, '\\u0024{');
}

const world = read(WORLD_SOURCE);
const region = narrow(read(REGION_SOURCE), (geometry: GeometryObject<Properties>) =>
  REGION.has(String(geometry.id ?? '')),
);

const countries = region.objects['countries'];
const kept = countries?.type === 'GeometryCollection' ? countries.geometries.length : 0;
if (kept !== REGION.size) {
  throw new Error(
    `The atlas kept ${String(kept)} of ${String(REGION.size)} countries. An id in REGION is not in the source.`,
  );
}

const source = `// Generated by \`pnpm --filter @vertex/ui atlas\`. Do not edit.
//
// Geometry: Natural Earth (public domain), via world-atlas.
// Region: ${[...REGION.values()].join(', ')}.
import type { Topology } from 'topojson-specification';

/** The world's coastline, coarse: what is under the map when it is zoomed out. */
export const WORLD: Topology = JSON.parse(String.raw\`${embed(world)}\`) as Topology;

/** The countries of this edition's region, with the borders between them. */
export const REGION: Topology = JSON.parse(String.raw\`${embed(region)}\`) as Topology;

/** ISO 3166-1 numeric code of the country this edition is sold in. */
export const HOME = '${HOME}';
`;

const here = dirname(fileURLToPath(import.meta.url));
// From dist/geo back to the committed source beside this file's own original.
const target = resolve(here, '../../src/geo/atlas.generated.ts');
writeFileSync(target, source, 'utf8');

const kb = (text: string): string => `${String(Math.round(Buffer.byteLength(text) / 1024))} kB`;
console.log(
  `atlas: ${String(kept)} countries, world ${kb(embed(world))}, region ${kb(embed(region))}, file ${kb(source)}`,
);
